---
config_dir: "/etc/skydive"
log_dir: "/var/log/skydive"
log_level: "DEBUG"
skydive_image: 10.240.201.50:8890/visualizer/skydive
skydive_ui_image: 10.240.201.50:8890/visualizer/skydive_ui
pull_image: "yes"

# Webui Configuration
webui_port: 8301

# Analyzer Configuration
analyzer_port: 8304
analyzer_address: 10.60.17.243

# Docker Configuration
docker_proc_mount: "/host/proc"

# Neutron authentication
keystone_auth_url: "http://10.240.201.118:5000"
keystone_tenant_name: "admin"
keystone_region_name: "RegionOne"
keystone_domain_name: "Default"
openstack_password_prompt: "no"

# LLDP configuration
lldp_interfaces: ""
lldp_ignore_dcbx: "true"
lldp_timeout: "1m"
lldp_interval: "30s"

# SNMP Configuration
snmp_community: "public"
snmp_polling_interval: 10s
