---
config_dir: "/etc/skydive"
log_dir: "/var/log/skydive"
log_level: "INFO"
skydive_image: nexus.5f.cloud:8890/visualizer/skydive
skydive_ui_image: nexus.5f.cloud:8890/visualizer/skydive_ui

# Analyzer Configuration
analyzer_port: 8304

# Docker Configuration
docker_proc_mount: "/host/proc"

# Neutron authentication
keystone_auth_url: "http://10.240.201.118:5000"
keystone_tenant_name: "admin"
keystone_region_name: "RegionOne"
keystone_domain_name: "Default"
openstack_password_prompt: "no"

# LLDP configuration
lldp_interfaces: ""
lldp_ignore_dcbx: "true"
lldp_disable_after: "30m"
lldp_remove_after: "2160m"

# SNMP Configuration
snmp_community: "public"
snmp_polling_interval: 300