---
- name: Ansible playbook
  hosts: analyzer
  gather_facts: no
  tasks:
    - name: Create directories
      file:
        name: "{{ item }}"
        state: directory
      with_items:
        - /etc/skydive/analyzer/
        - /var/log/skydive/analyzer/
    - name: Create configuration file
      template:
        src: ./templates/analyzer.j2
        dest: /etc/skydive/analyzer/skydive.conf
    - name: Run analyzer
      docker_container:
        name: visualizer_analyzer
        image: 10.240.201.50:8890/visualizer/skydive
        pull: yes
        network_mode: host
        mounts: 
          - type: bind
            source: /etc/skydive/analyzer
            target: /etc/skydive
          - type: bind
            source: /var/log/skydive/analyzer
            target: /var/log/skydive
        command: "/root/skydive analyzer --conf /etc/skydive/skydive.conf --listen 0.0.0.0:8304"
        privileged: yes
        state: started
        restart: yes
